### ISSUE TITLE
Lojistik regresyonda overfitten kurtulmalıyız.

### ISSUE THREAD

**Issue by ibaytar** [f1rzen/IST491#19]
Lojistik regresyonda overfit olduğu düşünülüyor. Confussion matrix 0 lı olmamalı.

![image](https://github.com/f1rzen/IST491/assets/66115781/af583f58-3561-4946-a971-431b85ac6d81)

**Comment by AshNumpy** [comment]
Overfit olmaya karşı Naive Bayes modelini kullanabiliriz. @f1rzen Senin de bu fikre katılman durumunda seçilen modeli naive Bayes olacak şekilde güncelleyeceğim.

![image](https://github.com/f1rzen/IST491/assets/92748453/1e72161c-7e98-4ddf-8b7f-118123ebe960)

* Model: Naive Bayes
* Train Accuracy: 0.88875
* Test Accuracy: 0.895
* Precision: 0.9076568592697626
* Recall: 0.8864099766538791

**Train Confusion matrix**
 [266   0  17]
 [  8 226  14]
 [ 50   0 219]

**Test Confusion matrix**
 [79  0  3]
 [ 2 47  6]
 [10  0 53]
