### ISSUE TITLE
Streamlit Arayüz Tasarımı

### ISSUE THREAD

**Issue by ibaytar** [f1rzen/IST491#21]
Bento Grid'ten esinlenilerek yapılan arayüzler. Grid için pico.css te bulunun `.grid` classı, card için `article` elementi kullanılabilir.

![WhatsApp Görsel 2024-05-10 saat 16 12 09_b2555185](https://github.com/f1rzen/IST491/assets/66115781/b03aaa43-5a40-4003-90c1-e7405f9a59e2)

**Comment by AshNumpy** [comment]
@f1rzen Css için fikir vermesi açısından [bu repoya](https://github.com/AshNumpy/CSS-In-Streamlit) bir göz atabilirsin

**Comment by AshNumpy** [comment]
#23 PR'ı ile bu issue'yu kapatıyorum.
