### ISSUE TITLE
Clustering Analysis

### ISSUE THREAD

**Issue by AshNumpy** [f1rzen/IST491#5]

**Comment by AshNumpy** [comment]
Kümeleme analizi ile standartlaştırılmış veri noktalarının birbiri ile olan ilişkisi incelenip küme sayısı belirlenmeli. Belirlenen küme sayısı ilgili veri noktalarına atanmalı (Örn. küme sayısı 3 olarak belirlendi, 1. satır 1 numaralı kümeye ait 2. satır 2 numaralı kümeye ait etc.)

**Comment by AshNumpy** [comment]
"Kümeleme Analizi ve PCA" başlıklı PR ile kapatılabilir @f1rzen

**Comment by ibaytar** [comment]
Eklendi
